In [2]:
import numpy as np

In [35]:
#Printing Numpy Version:
print(np.__version__)

1.26.4


In [33]:
#A Simple Numpy Array:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [37]:
#Printing the array type:
print(type(arr))

<class 'numpy.ndarray'>


In [38]:
#0D Array- No array just a value:
zeroD=np.array(13)
print(zeroD)

13


In [39]:
#1D Array- A simple one dimension array:
oneD = np.array([1, 2, 3, 4, 5])
print(oneD)

[1 2 3 4 5]


In [40]:
#2D Array- An array with 2 arrays within:
twoD = np.array([[1, 2, 3], [4, 5, 6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


In [41]:
#3D Array- Arrays within an array:
threeD = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(threeD)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [42]:
#Check the dimentions of array:
myarray= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(myarray.ndim)

3


In [43]:
#Setting dimensions of an array:
dim = np.array([1, 2, 3, 4], ndmin=5)

print(dim)
print('number of dimensions :', dim.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [2]:
#Getting an element by its index:
indarr = np.array([1, 2, 3, 4])
print(indarr[0])

1


In [4]:
#Operations on values using their indexes:
addind = np.array([1, 2, 3, 4])
print(addind[2] + addind[3])

7


In [6]:
#Accessing elements on 2D array:
twod = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', twod[0, 1]) #just as the nested tuples are accessed

2nd element on 1st row:  2


In [7]:
#Accessing 3D arrays:
threed = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threed[0, 1, 2])

6


In [8]:
#Negative indexing- accessing the array from behind (-1st element is the last element):
negarr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', negarr[1, -1])

Last element from 2nd dim:  10


In [9]:
#Array slicing:
slicearr = np.array([1, 2, 3, 4, 5, 6, 7])
print(slicearr[1:5])

[2 3 4 5]


In [3]:
#Slicing from a particular index to last:
endslicearr = np.array([1, 2, 3, 4, 5, 6, 7])
print(endslicearr[4:])

[5 6 7]


In [4]:
#Slicing from start to particular index:
startslicearr = np.array([1, 2, 3, 4, 5, 6, 7])
print(startslicearr[:4])

[1 2 3 4]


In [5]:
#Negative SLicing:
negslice = np.array([1, 2, 3, 4, 5, 6, 7])
print(negslice[-3:-1])

[5 6]


In [7]:
#Access the elements alternately, within particular indexes:
stparr = np.array([1, 2, 3, 4, 5, 6, 7])
print(stparr[1:5:2])

[2 4]


In [8]:
#Access all the elements alternately:
altarr = np.array([1, 2, 3, 4, 5, 6, 7])
print(altarr[::2])

[1 3 5 7]


In [10]:
#Slicing 2D array:
oneslicearr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(oneslicearr[0:2, 2]) #2 is the address of second row

[3 8]


In [13]:
#SLicing from both arrays in a 2D array:
bothslicearr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(bothslicearr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [16]:
#Checking the datatype of the elements in the array:
dttype = np.array(['apple', 'banana', 'cherry'])
print(dttype.dtype) #U6 refers to unicode string

<U6


In [17]:
#Creating an array with defined datatype:
dtypearr = np.array([1, 2, 3, 4], dtype='S')
print(dtypearr)
print(dtypearr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
#Assigning datatype with size:
dtsizearr = np.array([1, 2, 3, 4], dtype='i4') #integer of 4 bytes
print(dtsizearr)
print(dtsizearr.dtype)

[1 2 3 4]
int32


In [20]:
#Non converted datatypes:
wrongarr = np.array(['a', '2', '3'], dtype='i')
print(wrongarr)
print(wrongarr.dtype) #will throw an error because of wrong datatype

ValueError: invalid literal for int() with base 10: 'a'

In [21]:
#Changing datatype of an already created array:
arrone = np.array([1.1, 2.1, 3.1])
arrtwo = arrone.astype('i')

print(arrtwo)
print(arrtwo.dtype)

[1 2 3]
int32


In [23]:
#Change data type from integer to boolean:
arrint = np.array([1, 0, 3])

arrbool = arrint.astype(bool) #Converts zeros into false

print(arrbool)
print(arrbool.dtype)

[ True False  True]
bool


In [28]:
#Copy of an array- Copy is a new array that exists as copy of the previous one:
copyarr = np.array([1, 2, 3, 4, 5])
new = copyarr.copy()
copyarr[0] = 42

print(copyarr)
print(new)

[42  2  3  4  5]
[1 2 3 4 5]


In [29]:
#Making a view of an array- View is just a view of the array:
viewarr = np.array([1, 2, 3, 4, 5])
newv = viewarr.view()
viewarr[0] = 42

print(viewarr)
print(newv)

[42  2  3  4  5]
[42  2  3  4  5]


In [30]:
#The changes made in view affect the original array:
viewar = np.array([1, 2, 3, 4, 5])
newview = viewar.view()
newview[0] = 31

print(viewar)
print(newview)

[31  2  3  4  5]
[31  2  3  4  5]


In [31]:
#Checking if array owns its data- Copy owns the data, View does'nt:
arrown = np.array([1, 2, 3, 4, 5])

x = arrown.copy()
y = arrown.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [33]:
#Checking the shape of an array:
arrshp = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arrshp.shape) #Gives the number of rows and columns

(2, 4)


In [ ]:
#Checking the shape of 5D array:
arrfive = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

In [4]:
#Reshaping an array:
arrres = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

reshaped = arrres.reshape(4, 3) #4 rows with 3 values
print(reshaped)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
#Reshaping from 1D to 3D:
onedarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

threedarr = onedarr.reshape(2, 3, 2)
print(threedarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
#Flattening the array- reshaping to decrease the dimension degreeL
oriarr = np.array([[1, 2, 3], [4, 5, 6]])

flatarr = oriarr.reshape(-1) #Reduce one dimension
print(flatarr)

[1 2 3 4 5 6]


In [10]:
#Iterating each value in an array:
itrarr = np.array([1, 2, 3])

for i in itrarr:
  print(i)

1
2
3


In [12]:
#Iterating 2D arrays:
itrtwoarr = np.array([[1, 2, 3], [4, 5, 6]])

for i in itrtwoarr:
  print(i) #iterates the sub-arrays

[1 2 3]
[4 5 6]


In [13]:
#Iterating each single value of a 2D array instead of whole consituent arrays:
ittrarr = np.array([[1, 2, 3], [4, 5, 6]])

for i in ittrarr:
  for j in i:
    print(j)

1
2
3
4
5
6


In [14]:
#Iterating each single value of a 3D array instead of whole consituent arrays:
itttrarr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in itttrarr:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
#Shorter method for above:
itttrsarr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in np.nditer(itttrsarr):
  print(i)

1
2
3
4
5
6
7
8


In [16]:
#Iterating different datatypes:
dttarr = np.array([1, 2, 3])

for i in np.nditer(dttarr, flags=['buffered'], op_dtypes=['S']):
  print(i)

b'1'
b'2'
b'3'


In [17]:
#Alternate iteration:
altitrarr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i in np.nditer(altitrarr[:, ::2]):
  print(i)

1
3
5
7


In [19]:
#Iterating along with the address of the element (enumeration):
enuarr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idi, i in np.ndenumerate(enuarr):
  print(idi, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [21]:
#Joining basic arrays using concatenate function:
firstarr = np.array([1, 2, 3])
secondarr = np.array([4, 5, 6])

finalarr = np.concatenate((firstarr, secondarr))
print(finalarr)

[1 2 3 4 5 6]


In [23]:
#Joining 2D arrays using concatenate:
arrfirst = np.array([[1, 2], [3, 4]])
arsecond = np.array([[5, 6], [7, 8]])

arrfinal = np.concatenate((arrfirst, arsecond), axis=1) #Each 2D array becomes 1D and the result array is 2D
print(arrfinal)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
#Joining using stack function:
arrstack1 = np.array([1, 2, 3])
arrstack2 = np.array([4, 5, 6])

arrstacked = np.stack((arrstack1, arrstack2), axis=1) #Created a 2D array
print(arrstacked)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
#Stacking along rows:
arrrow1 = np.array([1, 2, 3])
arrrow2 = np.array([4, 5, 6])

arrrows = np.hstack((arrrow1, arrrow2)) #Arranges horizontally
print(arrrows)

[1 2 3 4 5 6]


In [31]:
#Stacking along columns:
arrcol1 = np.array([1, 2, 3])
arrcol2 = np.array([4, 5, 6])

arrcols = np.vstack((arrcol1, arrcol2)) #Arranges vertically as a 2D array
print(arrcols)

[[1 2 3]
 [4 5 6]]


In [34]:
#Stacking along height (Depth):
arrhei1 = np.array([1, 2, 3])
arrhei2 = np.array([4, 5, 6])

arrhei = np.dstack((arrhei1, arrhei2)) #One from first array and one from another made into tiny arrays
print(arrhei)

[[[1 4]
  [2 5]
  [3 6]]]


In [36]:
#Spliting the array:
onearr = np.array([1, 2, 3, 4, 5, 6])
slparr = np.array_split(onearr, 3) #Divides the above array into three arrays

print(slparr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [38]:
#Printing each splitted array individually:
print(slparr[0])
print(slparr[1])
print(slparr[2])

[1 2]
[3 4]
[5 6]


In [39]:
#Splitting 2D array:
arrnew = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
splitarr = np.array_split(arrnew, 3)

print(splitarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [42]:
#Splitting along rows:
arrfull = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
rowarr = np.array_split(arrfull, 3, axis=1) #Each element of each array as a single element array in three arrays

print(rowarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [43]:
#ALternate method for above- opposite to hstack:
abovearr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
nabovearr = np.hsplit(abovearr, 3)

print(nabovearr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [45]:
#Searching an element in the array using 'where':
givenarr = np.array([1, 2, 3, 4, 5, 4, 4])

i = np.where(givenarr == 4) #index of the positions where the given elements exist
print(i)

(array([3, 5, 6], dtype=int64),)


In [47]:
#Search the even numbers in the array by index:
thisarr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(thisarr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [49]:
#Searchsort- gives the index of where an element should be added to keep the array sorted:
existarr = np.array([6, 8, 9, 10])

x = np.searchsorted(existarr, 7)
print(x)

1


In [51]:
#Doing above on multiple elements:
arrthis = np.array([1, 3, 5, 7])

x = np.searchsorted(arrthis, [2, 4, 6]) #Numbers could be entered at the given indexes (it tries the first,and then the scond, and then the third)
print(x)

[1 2 3]


In [52]:
#Sorting an array:
unsortedarr = np.array([3, 2, 0, 1])
print(np.sort(unsortedarr))

[0 1 2 3]


In [53]:
#Sorting the string values alphabetically:
unsoarr = np.array(['banana', 'cherry', 'apple', 'blueberry'])
print(np.sort(unsoarr))

['apple' 'banana' 'blueberry' 'cherry']


In [55]:
#Sorting the boolean values:
unarr = np.array([True, False, True]) #It is basically sorted in alphabetical order meaning false would come first
print(np.sort(unarr))

[False  True  True]


In [57]:
#Sorting 2D array:
twounsortedarr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(twounsortedarr)) #sorts each sub array internally

[[2 3 4]
 [0 1 5]]


In [58]:
#Filtering the arrays:
arrtofilter = np.array([41, 42, 43, 44])
x = [True, False, True, False] #Corresponds to each value in the array
filteredarr = arrtofilter[x]

print(filteredarr)

[41 43]


In [61]:
#Creating filter to sort out even and odd in an array:
oldarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filter_arr = [] #Create an empty list

for element in oldarr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = oldarr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [63]:
#Doing above by directly creating filter from the array:
prevarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filter_arr = prevarr % 2 == 0

newarr = prevarr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False  True False]
[2 4 6 8]


In [64]:
#For using 'random' function:
from numpy import random

In [65]:
#Generating a random number:
x = random.randint(100) #number between 1- 100
print(x)

79


In [66]:
#Generating random float:
x = random.rand()
print(x)

0.35226303473737697


In [67]:
#Generating random array:
x=random.randint(100, size=(5)) #An array with 5 elements having random values between 1-100 
print(x)

[36 70 67 79 37]


In [71]:
#Similarly, we can create an array with floats:
x = random.rand(5)
print(x)

[0.20391509 0.92451172 0.80567139 0.74127506 0.99831511]


In [68]:
#Creating multidimensional array with random values:
x = random.randint(100, size=(3, 5)) #2D
print(x)

[[67 20 32 21 25]
 [45 91 60 83 30]
 [58 71 19 83  8]]


In [70]:
x = random.randint(100, size=(3, 5, 2)) #3D
print(x)

[[[19 33]
  [50 64]
  [ 8 50]
  [18 20]
  [21 65]]

 [[72  7]
  [60 74]
  [96  3]
  [37 33]
  [95 98]]

 [[62 36]
  [18 76]
  [33 96]
  [60 42]
  [83 62]]]


In [72]:
#Pick a random element from an array:
x = random.choice([3, 5, 7, 9])
print(x)

5


In [74]:
#From the given array, generate 2D array with the elements in given array at different positions:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[5 9 9 5 7]
 [9 5 9 9 9]
 [5 9 7 7 9]]
